name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: "Build, Test, and Report Coverage"
    runs-on: ubuntu-latest
    permissions:
      # Required to allow actions/checkout to clone the repository onto the runner
      contents: read
      # Required to allow the vitest coverage action to write a comment into the pull request
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm run test
      - name: 'Report Coverage'
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          vite-config-path: vite.config.ts
